### ISSUE TITLE
Cyrillic character sent by game instead of Latin character

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#239]
```
[Master HamsterKombat Bot][INFO] 2024-08-27 02:03:55 [Account 10] Best upgrade is Сoindesk with profit 193 and price 159.84k, Level: 14
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0421' in position 85: character maps to <undefined>
Call stack:
  File "C:\Users\FARM\Downloads\Hamster Kombat\MasterHamsterKombatBot-main-7\main.py", line 1554, in <module>
    main()
  File "C:\Users\FARM\Downloads\Hamster Kombat\MasterHamsterKombatBot-main-7\main.py", line 1548, in main
    asyncio.run(RunAccounts())
  File "C:\Users\FARM\Downloads\Hamster Kombat\MasterHamsterKombatBot-main-7\main.py", line 1515, in RunAccounts
    account.Start()
  File "C:\Users\FARM\Downloads\Hamster Kombat\MasterHamsterKombatBot-main-7\main.py", line 1409, in Start
    if not self.BuyBestCard():
  File "C:\Users\FARM\Downloads\Hamster Kombat\MasterHamsterKombatBot-main-7\main.py", line 718, in BuyBestCard
    log.info(
Message: '[Account 10] Best upgrade is Сoindesk with profit 193 and price 159.84k, Level: 14'
Arguments: ()
[Master HamsterKombat Bot][INFO] 2024-08-27 02:03:55 [Account 10] Attempting to buy the best card...
```

![error](https://github.com/user-attachments/assets/e1d30ee7-39b5-4707-89f0-756b848a2a1b)

I know this is because of the updates in https://github.com/masterking32/MasterHamsterKombatBot/pull/238 which have been fixed by adding https://github.com/masterking32/MasterHamsterKombatBot/pull/238/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R60 but it might be useful to know.

**Comment by masterking32** [comment]
We don't have any support for PRs, Just Merged PRs can be checked.
