### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by kasbyte** [masterking32/MasterHamsterKombatBot#340]
Traceback (most recent call last):
  File "c:\github\MasterHamsterKombatBot\main.py", line 1643, in <module>
    main()
  File "c:\github\MasterHamsterKombatBot\main.py", line 1637, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "c:\github\MasterHamsterKombatBot\main.py", line 1604, in RunAccounts
    account.Start()
  File "c:\github\MasterHamsterKombatBot\main.py", line 1425, in Start
    rewardCoins = streak_days["rewardCoins"]
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'rewardCoins'

**Comment by AmirhN1382** [comment]
No issue, make sure to use latest version of the bot.

**Comment by kasbyte** [comment]
thanks

**Comment by AmirhN1382** [comment]
Update the bot. It's solved in latest version
