### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by camillo1991** [masterking32/MasterHamsterKombatBot#353]
Hi! A have this bug after launch:
[31m[Master HamsterKombat Bot][0m[[31mERROR[0m] [31m[Alexey] Error: HTTPSConnectionPool(host='api.hamsterkombatgame.io', port=443): Max retries exceeded with url: /clicker/upgrades-for-buy (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002CF6E02F7C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))[0m
[31m[Master HamsterKombat Bot][0m[[31mERROR[0m] [31m[Alexey] Error: HTTPSConnectionPool(host='api.hamsterkombatgame.io', port=443): Max retries exceeded with url: /clicker/upgrades-for-buy (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002CF6E02FC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))[0m
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1239, in <module>
    main()
  File "C:\Users\Administrator\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1233, in main
    asyncio.run(RunAccounts())
  File "C:\Users\Administrator\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1200, in RunAccounts
    account.Start()
  File "C:\Users\Administrator\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1134, in Start
    for item in upgradesResponse["upgradesForBuy"]
TypeError: 'bool' object is not subscriptable

**Comment by Fy0urM** [comment]
> Caused by ProxyError('Unable to connect to proxy',

something wrong with your proxy
