### ISSUE TITLE
Config is issue

### ISSUE THREAD

**Issue by camillo1991** [masterking32/MasterHamsterKombatBot#365]
Hello! Config file is a issue in repo
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Crypto\HamsterKombatBot\main.py", line 19, in <module>
    from config import *
  File "C:\Users\Administrator\Desktop\Crypto\HamsterKombatBot\config.py", line 334
    },
    ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' on line 13

**Comment by camillo1991** [comment]
That was my mistake, I was running one code and editing another xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
