### ISSUE TITLE
Errors in the bot.py its not working tell me: name clear_screen in not defined 

### ISSUE THREAD

**Issue by Gohany127** [masterking32/MasterHamsterKombatBot#415]
Traceback (most recent call last): File "/home/container/bot.py", line 2298, in <module> main() File "/home/container/bot.py", line 2286, in main clear_screen() NameError: name 'clear_screen' is not defined
Please help me

**Comment by Gohany127** [comment]
Bro can make tool as hamster for other games plz you are the best one ❤️‍🔥
