### ISSUE TITLE
Error while running .exe

### ISSUE THREAD

**Issue by vashamamasha2014** [masterking32/MasterHamsterKombatBot#449]
![Screenshot_1](https://github.com/user-attachments/assets/f0e2c5dc-9302-4477-9e6a-53ec6d273f9d)

Раньше When compiling in .exe via PyInstaller with the parameter -noconsole 
```
pyinstaller --onefile --noconsole --add-data "C:\Users\user\PycharmProjects\BD_Viewer\MasterHamsterKombatBot\config.py;." --add-data "C:\Users\user\PycharmProjects\BD_Viewer\MasterHamsterKombatBot\utilities.py;." --add-data "C:\Users\user\PycharmProjects\BD_Viewer\MasterHamsterKombatBot\promogames.py;." --add-data "C:\Users\user\PycharmProjects\BD_Viewer\MasterHamsterKombatBot\useful_files;useful_files" --add-data "C:\Users\user\PycharmProjects\BD_Viewer\MasterHamsterKombatBot\banner.py;." --add-data "C:\Users\user\PycharmProjects\BD_Viewer\MasterHamsterKombatBot\warna.py;." C:\Users\user\PycharmProjects\BD_Viewer\MasterHamsterKombatBot\main.py``` , the version of the bot in which the loading bar and banner appeared gives an error when launched: 
Traceback (most recent call last):
  File "main.py", line 2300, in <module>
  File "main.py", line 2290, in main
  File "main.py", line 2277, in loading_bar2
AttributeError: 'NoneType' object has no attribute 'write'




The answer should be found in "sys.stdout", please fix it in the next patch.

**Comment by Fy0urM** [comment]
In the original, pyinstaller does not need to specify all files, by specifying 1 main.py file it will automatically pull up all imports. Try not to add all files manually

**Comment by Fy0urM** [comment]
try just 'pyinstaller --onefile main.py'

**Comment by vashamamasha2014** [comment]
> try just pyinstaller --onefile main.py

This happens when exactly "-noconsole", I need a silent start.

**Comment by vashamamasha2014** [comment]
> try just `pyinstaller --onefile main.py`

![image](https://github.com/user-attachments/assets/e622f9cf-2afa-42f6-89cd-fb1268065a99)

**Comment by Fy0urM** [comment]
I see, in that case, I can't help you.

**Comment by Fy0urM** [comment]
You can try commenting out the for loop within which stdout is used, this will disable the banner display but should help if stdout is not used anywhere else.

**Comment by vashamamasha2014** [comment]
> You can try commenting out the for loop within which stdout is used, this will disable the banner display but should help if stdout is not used anywhere else.

I have solved the problem, please fix it in your main code so that users do not have problems with this in the future, thank you.
There are two functions that need to be fixed: 
```
def loading_bar(duration):
    bar_length = 40
    end_time = time.time() + duration
    while time.time() < end_time:
        for i in range(bar_length + 1):
            percent = (i / bar_length) * 100
            bar = "█" * i + "-" * (bar_length - i)
            print(f"\r[{bar}] {percent:.2f}%", end='', flush=True)
            time.sleep(duration / bar_length)  # Adjust the duration for each step

    # Clear the loading bar
    print("\r" + " " * (bar_length + 8) + "\r", end='', flush=True)

if __name__ == "__main__":
    loading_bar(4)
```

+ 
```
def loading_bar2(duration):
    total_steps = 20
    interval = duration / total_steps

    print("Loading:", end=" ", flush=True)

    for i in range(1, total_steps + 1):
        print(f"\rLoading: {'█' * i}{' ' * (total_steps - i)} {int(i * 100 / total_steps)}%", end="", flush=True)
        time.sleep(interval)

    print(f"\rLoading: {'█' * total_steps} 100%", flush=True)
```

**Comment by vashamamasha2014** [comment]
> I'm afraid that users who don't want to use the code provided by the author according to the instructions provided by the author will have to solve their problems themselves).

I don't see any difficulties for you, as one of the developers who actively participates in the development of this bot, to apply this code. Moreover, it does not violate the functionality of the loading bar. Github is needed for this, to share developments, and so that each user can contribute to the common cause)

**Comment by masterking32** [comment]
We do not support or release any executable (.exe) files, as they are not related to the project.
