### ISSUE TITLE
Code Error 

### ISSUE THREAD

**Issue by Microzibert** [masterking32/MasterHamsterKombatBot#453]
Code gets stuck 
```
[MasterHamsterKombatBot] [2024-09-16 06:38:41] [ERROR] [Twink_1]: ✖ Error: HTTPS
ConnectionPool(host='api.hamsterkombatgame.io', port=443): Read timed out. (read
 timeout=30)
Traceback (most recent call last):
  File "main.py", line 2307, in <module>
    main()
  File "main.py", line 2301, in main
    asyncio.run(RunAccounts())
  File "main.py", line 2255, in RunAccounts
    account.Start()
  File "main.py", line 1839, in Start
    self.configData = AccountConfigVersionData.get("config", {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by AmirhN1382** [comment]
Either your network issue or Hamster servers as you can see in the error.
