### ISSUE TITLE
How to fix Traceback (most recent call last)

### ISSUE THREAD

**Issue by teampanditofficial** [masterking32/MasterHamsterKombatBot#455]
Traceback (most recent call last):
  File "/opt/render/project/src/main.py", line 2310, in <module>
    main()
  File "/opt/render/project/src/main.py", line 2304, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "/opt/render/project/src/main.py", line 2258, in RunAccounts
    account.Start()
  File "/opt/render/project/src/main.py", line 1842, in Start
    self.configData = AccountConfigVersionData.get("config", {})
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
127.0.0.1 - - [17/Sep/2024 05:54:52] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2024 05:59:52] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2024 06:04:52] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2024 06:09:52] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2024 06:14:52] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2024 06:19:52] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2024 06:24:52] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2024 06:29:52] "HEAD / HTTP/1.1" 200 -

**Comment by teampanditofficial** [comment]
When i run the code for 24/7 after 24 hrs it stops and gives this messgae in the console logs

**Comment by teampanditofficial** [comment]
How to fix it is the problem with the script or with the console terminal itself
