### ISSUE TITLE
Major faults, how to solve them

### ISSUE THREAD

**Issue by 284267** [masterking32/MasterHamsterKombatBot#456]
![Uploading image.png…]()

**Comment by 284267** [comment]
</div>
</div>
</body>
</html>

Traceback (most recent call last):
  File "/root/MasterHamsterKombatBot/cs.py", line 2321, in <module>
    main()
  File "/root/MasterHamsterKombatBot/cs.py", line 2315, in main
    asyncio.run(RunAccounts())
  File "/root/MasterHamsterKombatBot/cs.py", line 2269, in RunAccounts
    account.Start()
  File "/root/MasterHamsterKombatBot/cs.py", line 1830, in Start
    self.configData = AccountConfigVersionData.get("config", {})
AttributeError: 'NoneType' object has no attribute 'get'
