### ISSUE TITLE
Error with Multi Acc.

### ISSUE THREAD

**Issue by Komeylk** [masterking32/MasterHamsterKombatBot#52]
Traceback (most recent call last):
  File "C:\Users\****************\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1014, in <module>
    main()
  File "C:\Users\****************\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1008, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "C:\Users\****************\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 975, in RunAccounts
    account.Start()
  File "C:\Users\****************\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 874, in Start
    if self.config["wait_for_best_card"]:
       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'wait_for_best_card'

**Comment by Komeylk** [comment]
solve it.
