### ISSUE TITLE
In the latest update the following error appears

### ISSUE THREAD

**Issue by bangtony2** [masterking32/MasterHamsterKombatBot#54]
Status code is not 200
Response: {"error_code":"UPGRADE_COOLDOWN","error_message":"Upgrade 'appstore_launch' on cooldown 618 seconds","upgradeId":"appstore_launch","cooldownSeconds":618}
![image](https://github.com/user-attachments/assets/dfad7619-5ee6-4a2c-ab73-18c31ec8a84e)

**Comment by bangtony2** [comment]
@masterking32
 
```
Traceback (most recent call last):
  File "C:\Users\bangtony\Desktop\new\hbot\bot.py", line 1157, in <module>
    main()
  File "C:\Users\bangtony\Desktop\new\hbot\bot.py", line 1151, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "C:\Users\bangtony\Desktop\new\hbot\bot.py", line 1123, in RunAccounts
    account.Start()
  File "C:\Users\bangtony\Desktop\new\hbot\bot.py", line 1015, in Start
    if not self.BuyBestCard():
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bangtony\Desktop\new\hbot\bot.py", line 579, in BuyBestCard
    FindBestCardWithLowerCoefficient(
  File "C:\Users\bangtony\Desktop\new\hbot\utilities.py", line 20, in FindBestCardWithLowerCoefficient
    cards = SortUpgrades(upgrades, 999_999_999_999_999)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bangtony\Desktop\new\hbot\utilities.py", line 10, in SortUpgrades
    upgrades = [item for item in upgrades if item["price"] <= max_budget]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object is not iterable
```
