### ISSUE TITLE
crash bot

### ISSUE THREAD

**Issue by AlexArGC** [masterking32/MasterHamsterKombatBot#67]
What could cause the bot to fall? This happens after some time of operation.

```
...
[Master HamsterKombat Bot][ERROR] [P2] Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
...
[Master HamsterKombat Bot][ERROR] [U2] Error: HTTPSConnectionPool(host='api.hamsterkombatgame.io', port=443): Max retries exceeded with url: /clicker/upgrades-for-buy (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002D9D7340890>, 'Connection to api.hamsterkombatgame.io timed out. (connect timeout=None)'))
...
[Master HamsterKombat Bot][ERROR] [U2] Error: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
...
[Master HamsterKombat Bot][INFO] [U3] Checking for best card...
[Master HamsterKombat Bot][ERROR] [U3] Error: HTTPSConnectionPool(host='api.hamsterkombatgame.io', port=443): Max retries exceeded with url: /clicker/upgrades-for-buy (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002D9D73419A0>, 'Connection to api.hamsterkombatgame.io timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "C:\Crypts\Hamster\main.py", line 1401, in <module>
    main()
  File "C:\Crypts\Hamster\main.py", line 1395, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "C:\Crypts\Hamster\main.py", line 1362, in RunAccounts
    account.Start()
  File "C:\Crypts\Hamster\main.py", line 1262, in Start
    if not self.BuyBestCard():
           ^^^^^^^^^^^^^^^^^^
  File "C:\Crypts\Hamster\main.py", line 822, in BuyBestCard
    for item in upgradesResponse["upgradesForBuy"]
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

**Comment by AlexArGC** [comment]
Sorry, it looks like the problem is due to a lack of free RAM.
