### ISSUE TITLE
Error adding multiple accounts

### ISSUE THREAD

**Issue by BlessedUzama** [masterking32/MasterHamsterKombatBot#95]
i keep getting this error after i add another account
PS C:\Users\uzama.BLESSED_UZAMA\OneDrive\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main> python main.py
[Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] Welcome to [Master Hamster Kombat] Auto farming bot...
[Master HamsterKombat Bot][INFO] Project Github: https://github.com/masterking32/MasterHamsterKombatBot
[Master HamsterKombat Bot][INFO] Developed by: MasterkinG32
[Master HamsterKombat Bot][INFO] Version: 2.2
[Master HamsterKombat Bot][INFO] To stop the bot, press Ctrl + C
[Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
[Master HamsterKombat Bot][INFO] ------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\uzama.BLESSED_UZAMA\OneDrive\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1433, in <module>
    main()
  File "C:\Users\uzama.BLESSED_UZAMA\OneDrive\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1427, in main
    asyncio.run(RunAccounts())
                ^^^^^^^^^^^^^
  File "C:\Users\uzama.BLESSED_UZAMA\OneDrive\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 1385, in RunAccounts
    accounts.append(HamsterKombatAccount(account))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uzama.BLESSED_UZAMA\OneDrive\Desktop\MasterHamsterKombatBot-main\MasterHamsterKombatBot-main\main.py", line 145, in __init__
    self.Proxy = AccountData["Proxy"]
                 ~~~~~~~~~~~^^^^^^^^^
KeyError: 'Proxy'

i dont really know what to do because am new to all this. i will really appreciate your help.

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot/discussions/33
